/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gt.edu.umg.progra3;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        /*ArrayStack arrayStack = new ArrayStack();
        arrayStack.push(3);
        arrayStack.push(0);
        arrayStack.pop();
        arrayStack.push(6);
        arrayStack.push(9);
        arrayStack.printAll();
        arrayStack.pop();*/
        /*Stack list = new Stack();
        list.push(3);
        list.push(4);
        list.pop();
        list.push(5);
        list.pop();
        list.pop();
        list.pop();
        list.printAll();*/
        Tree tree = new Tree();
        tree.insert(99, "Melvin", "0000000", "mcalic1@miumg.edu.gt");
        tree.insert(3, "Melvin2", "0000000", "mcalic1@miumg.edu.gt");
        tree.insert(16, "Melvin3", "0000000", "mcalic1@miumg.edu.gt");
        tree.insert(101, "Melvin4", "0000000", "mcalic1@miumg.edu.gt");
        tree.preorder();
        System.out.println("Inorden:");
        tree.inorder();
        System.out.println("Postorden:");
        tree.postorder();
    }
}
